### ISSUE TITLE
Languages supported?

### ISSUE THREAD

**Issue by drobati** [kovetskiy/next-indentation#2]
It wasn't exactly clear if this is just Go specific or even that it was specific for Go at first.

Looking through the page everything references Go, but no where does it specifically say it's just for Go's indentation.

Otherwise, very cool!

**Comment by kovetskiy** [comment]
Hello, @drobati 

Actually, it's not language specific plugin, but I program only in Go (python a little bit) and tested plugin only with Go.

If you detect some troubles with other languages, then please create issue, I'll glad to solve it.

**Comment by drobati** [comment]
Ah. Okay. :+1:
